server:
  port: 8082
spring:
  application:
    name: flow-eda-logger
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:public}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
