server:
  port: 8088
spring:
  application:
    name: flow-eda-runner
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:public}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    log_exchange: flow.log
    log_routing_key: flow.running.log
security:
  oauth2:
    resource-id: flow-eda
    client-id: 1df7b0c1-aac0-148a14c7cba8
    client-secret: zcUaT32GlwIjz4yBJjYZIIMvzf
    check-token-url: http://localhost:8086/oauth/check_token
