server:
  port: 8085
spring:
  application:
    name: flow-eda-runner
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:public}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
  # logger 下线，移除 rabbitmq 日志推送配置
